class DataBaseError(Exception): # Code 1001
    def __init__(self, error: Exception | None = None): ...

class VaildEmailError(Exception): ...
class MinecraftError(Exception): ... 

class UserNotFoundError(DataBaseError): ... 
class NotCorrectPasswordError(DataBaseError): ... 
class UserAlreadyExistsError(DataBaseError): ...
class UserAlreadyAddedError(DataBaseError): ...

class ModLoaderError(MinecraftError): ...
class ForgeLoaderError(ModLoaderError): ... 
class FabricLoaderError(ModLoaderError): ... 

class ForgeInstallError(ForgeLoaderError): ... 
class ForgeStartError(ForgeLoaderError): ... 

class FabricInstallError(FabricLoaderError): ... 
class FabricStartError(FabricLoaderError): ... 

class MinecraftInstallError(MinecraftError): ...
class MinecraftStartError(MinecraftError): ...
